coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 0.03%
        base: auto
comment:
  after_n_builds: 10 # Prevent early, spurious Codecov reports before all tests finish: https://github.com/kensho-technologies/graphql-compiler/pull/806#issuecomment-730622647. 10 is calculated here from the number of jobs to run, which is specified in the .github/workflows/tests_and_lint.yml file: 5 lint jobs (1 job per python-version) and 5 test jobs (1 job per python-version).
